//
// Created by Christian Kater on 19.01.19.
//

#ifndef DCPLIB_DCPCALLBACKTYPES_HPP
#define DCPLIB_DCPCALLBACKTYPES_HPP
enum class DcpCallbackTypes {
    PREPARE, CONFIGURE, SYNCHRONIZING_NRT_STEP, SYNCHRONIZED_NRT_STEP, RUNNING_NRT_STEP, STOP, TIME_RES, STEPS, OPERATION_INFORMATION, CONFIGURATION_CLEARED,
    RUNTIME, CONTROL_MISSED, IN_OUT_MISSED, PARAM_MISSED, STATE_CHANGED, ERROR_LI, INITIALIZE,
    ACK, NACK, STATE_ACK, ERROR_ACK, PDU_MISSED, DATA, RSP_log_ack, NTF_LOG, SYNCHRONIZING_STEP, SYNCHRONIZED_STEP, RUNNING_STEP, SYNCHRONIZE,
};

enum FunctionType {
    SYNC, ASYNC,
};
#endif //DCPLIB_DCPCALLBACKTYPES_HPP
